import type { Metadata } from "next";
import { Space_Grotesk, IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import "../scss/style.scss";
import GridContainer from "@/components/common/grid-container/GridContainer.component";
import Sidebar from "@/components/common/desktop/sidebar/Sidebar.component";
import Bottombar from "@/components/common/mobile/bottombar/Bottombar.component";
import FloatingSocialLinks from "@/components/common/floating-social-links/FloatingSocialLinks.component";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";

const ibmPlexSans = IBM_Plex_Sans({
  variable: "--font-ibm-plex-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ibmPlexSans.className} ${spaceGrotesk.variable} bg-background antialiased`}
      >
        <GridContainer cols={12}>
          <Sidebar />
          <main className="w-full h-full xl:col-span-10 col-span-full">
            {children}
          </main>
          <FloatingSocialLinks />
        </GridContainer>
        <Bottombar />
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
